# Generated by Django 6.1.2 on 2026-10-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('abbr', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('conference', models.CharField(blank=True, max_length=3)),
                ('division', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('season_type', models.CharField(max_length=4)),
                ('game_date', models.DateField(null=True)),
                ('home_score', models.IntegerField(null=True)),
                ('away_score', models.IntegerField(null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='stats.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.IntegerField()),
                ('quarter', models.IntegerField(null=True)),
                ('down', models.IntegerField(null=True)),
                ('yards_to_go', models.IntegerField(null=True)),
                ('yardline_100', models.IntegerField(null=True)),
                ('play_type', models.CharField(blank=True, max_length=16)),
                ('yards_gained', models.IntegerField(null=True)),
                ('epa', models.FloatField(null=True)),
                ('success', models.BooleanField(null=True)),
                ('win_prob', models.FloatField(null=True)),
                ('run_location', models.CharField(blank=True, max_length=8)),
                ('run_gap', models.CharField(blank=True, max_length=8)),
                ('pass_length', models.CharField(blank=True, max_length=8)),
                ('pass_location', models.CharField(blank=True, max_length=8)),
                ('passer', models.CharField(blank=True, max_length=64)),
                ('rusher', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='stats.game')),
                ('defense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defensive_plays', to='stats.team')),
                ('offense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offensive_plays', to='stats.team')),
            ],
            options={
                'indexes': [models.Index(fields=['offense', 'game'], name='stats_play_offense_40c6ef_idx'), models.Index(fields=['down', 'play_type'], name='stats_play_down_0f3e30_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'play_id'), name='unique_play_per_game')],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season', 'week'], name='stats_game_season_23e9b3_idx'),
        ),
    ]
